name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: echo "image_tag=${GITHUB_REF_NAME}-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag ghcr.io/lippesola/qr-homebox-redirect:${{ steps.tag.outputs.image_tag }}

      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u lippesola --password-stdin

      - name: Push the Docker image
        run: |
          docker push ghcr.io/lippesola/qr-homebox-redirect:${{ steps.tag.outputs.image_tag }}
