name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/lippesola/qr-homebox-redirect:${{ github.ref }}-$(date +%s)
    - name: Login to ghcr.io
      run: docker login ghcr.io -u lippesola -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Push the Docker image
      run: docker push ghcr.io/lippesola/qr-homebox-redirect:${{ GITHUB_REF }}-$(date +%s)
